server:
  port: 8888
# 服务名称
spring:
  application:
    name: spring-cloud-gateway
  # 开启 Gateway 服务注册中心服务发现
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-server
          uri: lb://oauth
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
# Eureka Server 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug


